---
title: "License"
---


## CC BY 4.0

<a href="https://creativecommons.org/licenses/by/4.0/" target="blank_"><strong>Creative Commons Attribution 4.0 International</strong></a>

This work is licensed under __CC BY 4.0__


### You are free to:

- __Share:__ copy and redistribute the material in any medium or format.

- __Adapt:__ remix, transform, and build upon the material.

- The licensor cannot revoke these freedoms as long as you follow the license terms.


### Under the following terms:

- __Attribution:__ You must give appropriate credit , provide a link to the license, 
and indicate if changes were made . You may do so in any reasonable manner, 
but not in any way that suggests the licensor endorses you or your use.

- __No additional restrictions:__ You may not apply legal terms or technological measures 
that legally restrict others from doing anything the license permits.


For more information, see <a href="https://creativecommons.org/licenses/by/4.0/" target="blank_">CC BY 4.0</a>

